import os
import pinecone
from db_utils import fetch_passages, fetch_english_passages, fetch_sentence_passages, fetch_bolded_words_passages
from embed_utils import generate_embeddings, add_openai_embeddings_to_passages